# This is a customization file for your own
# symbols database

# TODO: put here public repository id
FROM symbols

MAINTAINER roman.saveljev@haltian.com

# Tells how many path components to be stripped when
# adding symbols.
ENV STRIP_SYMBOLS_PATH 0
